name: libremidi
version: 0.1.0

github: ejconlon/libremidi-haskell
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: libremidi bindings for haskell
description: Please see the README on GitHub at <https://github.com/ejconlon/libremidi-haskell#readme>
tested-with: GHC == 9.6.6

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5
- data-default >= 0.7.1.1 && < 0.8
- containers >= 0.6.7 && < 0.7
- mtl >= 2.3.1 && < 2.4
- stm >= 2.5.1.0 && < 2.6
- text >= 2.0.2 && < 2.1
- transformers >= 0.6.1 && < 0.7

library:
  source-dirs: src
  extra-libraries:
  - stdc++
  include-dirs:
  - vendor
  cxx-sources:
  - vendor/libremidi/*.cpp
  when:
  - condition: os(darwin)
    cxx-options: -std=c++20 -DLIBREMIDI_COREMIDI=1
    frameworks: CoreMIDI CoreAudio CoreFoundation
    #   -- NOTE(ejconlon) This is to make the c ffi wrapper actually catch
    #   -- the c++ exceptions instead of simply aborting.
    #   -- Cribbed from https://github.com/fpco/inline-c/pull/89
    #   -- avoid https://gitlab.haskell.org/ghc/ghc/issues/11829
    ld-options: -Wl,-keep_dwarf_unwind
    ghc-options: -pgmcxx=clang++
  - condition: os(linux)
    cxx-options: -std=c++20 -DLIBREMIDI_PIPEWIRE=1 -DLIBREMIDI_HAS_UDEV=1
    ghc-options: -pgmcxx=clang++
    pkgconfig-depends:
    - libpipewire-0.3
    - udev

executables:
  libremidi-exe:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - libremidi

tests:
  libremidi-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - libremidi
    - tasty
    - tasty-hunit
