name: libremidi
version: 0.1.0

github: ejconlon/libremidi-haskell
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: libremidi bindings for haskell
description: Please see the README on GitHub at <https://github.com/ejconlon/libremidi-haskell#readme>
tested-with: GHC == 9.6.6

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5
- text >= 2.0.2 && < 2.1

library:
  source-dirs: src
  extra-libraries:
  - stdc++
  include-dirs:
  - vendor
  cxx-sources:
  - vendor/**/*.cpp
  cxx-options: -std=c++20 -DLIBREMIDI_HEADER_ONLY=1 -DLIBREMIDI_COREMIDI=1
  frameworks: CoreMIDI CoreAudio CoreFoundation
  #   -- NOTE(ejconlon) This is to make the c ffi wrapper actually catch
  #   -- the c++ exceptions instead of simply aborting.
  #   -- Cribbed from https://github.com/fpco/inline-c/pull/89
  #   -- avoid https://gitlab.haskell.org/ghc/ghc/issues/11829
  ld-options: -Wl,-keep_dwarf_unwind
  ghc-options: -pgmc=clang++

  # TODO(ejconlon) incorporate platform conditionals
  # if os(linux)
  #   if flag(alsa) && flag(jack)
  #     cxx-options:      -std=c++11 -D__LINUX_ALSA__ -D__UNIX_JACK__
  #     extra-libraries:  asound pthread jack
  #   if flag(alsa) && !flag(jack)
  #     cxx-options:      -std=c++11 -D__LINUX_ALSA__
  #     extra-libraries:  asound pthread
  #   if !flag(alsa) && flag(jack)
  #     cxx-options:      -std=c++11 -D__UNIX_JACK__
  #     extra-libraries:  jack
  #
  # if os(darwin)
  #   if flag(jack)
  #     cxx-options:      -std=c++11 -DTARGET_OS_IPHONE=0-D__MACOSX_CORE__ -D__UNIX_JACK__
  #     extra-libraries:  jack
  #   else
  #     cxx-options:    -std=c++11 -D__MACOSX_CORE__
  #   frameworks:       CoreMIDI CoreAudio CoreFoundation
  #   -- NOTE(ejconlon) This is to make the c ffi wrapper actually catch
  #   -- the c++ exceptions instead of simply aborting.
  #   -- Cribbed from https://github.com/fpco/inline-c/pull/89
  #   -- avoid https://gitlab.haskell.org/ghc/ghc/issues/11829
  #   ld-options:        -Wl,-keep_dwarf_unwind
  #   ghc-options:       -pgmc=clang++
  #
  # if os(mingw32)
  #   cxx-options:       -std=c++11 -D__WINDOWS_MM__
  #   extra-libraries:   winmm

executables:
  libremidi-exe:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - libremidi

tests:
  libremidi-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - libremidi
    - tasty
    - tasty-hunit
