name: libremidi
version: 0.4.2

github: ejconlon/libremidi-haskell
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: libremidi bindings for haskell
description: Please see the README on GitHub at <https://github.com/ejconlon/libremidi-haskell#readme>
tested-with: GHC == 9.8.4

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5
- data-default >= 0.7.1.1 && < 0.8
- containers >= 0.6.7 && < 0.7
- mtl >= 2.3.1 && < 2.4
- stm >= 2.5.1.0 && < 2.6
- text >= 2.0.2 && < 2.2
- transformers >= 0.6.1 && < 0.7

# Cabal doesn't seem to support globs here,
# so I have to find and copy names manually
install-includes:
- vendor/atomicops.h
- vendor/libremidi/api-c.h
- vendor/libremidi/libremidi-c.h
- vendor/readerwriterqueue.h
- vendor/libremidi/api.hpp
- vendor/libremidi/backends.hpp
- vendor/libremidi/backends/alsa_raw.hpp
- vendor/libremidi/backends/alsa_raw/config.hpp
- vendor/libremidi/backends/alsa_raw/error_domain.hpp
- vendor/libremidi/backends/alsa_raw/helpers.hpp
- vendor/libremidi/backends/alsa_raw/midi_in.hpp
- vendor/libremidi/backends/alsa_raw/midi_out.hpp
- vendor/libremidi/backends/alsa_raw/observer.hpp
- vendor/libremidi/backends/alsa_raw_ump.hpp
- vendor/libremidi/backends/alsa_raw_ump/config.hpp
- vendor/libremidi/backends/alsa_raw_ump/helpers.hpp
- vendor/libremidi/backends/alsa_raw_ump/midi_in.hpp
- vendor/libremidi/backends/alsa_raw_ump/midi_out.hpp
- vendor/libremidi/backends/alsa_raw_ump/observer.hpp
- vendor/libremidi/backends/alsa_seq.hpp
- vendor/libremidi/backends/alsa_seq/config.hpp
- vendor/libremidi/backends/alsa_seq/helpers.hpp
- vendor/libremidi/backends/alsa_seq/midi_in.hpp
- vendor/libremidi/backends/alsa_seq/midi_out.hpp
- vendor/libremidi/backends/alsa_seq/observer.hpp
- vendor/libremidi/backends/alsa_seq/shared_handler.hpp
- vendor/libremidi/backends/alsa_seq_ump.hpp
- vendor/libremidi/backends/alsa_seq_ump/config.hpp
- vendor/libremidi/backends/alsa_seq_ump/helpers.hpp
- vendor/libremidi/backends/alsa_seq_ump/midi_out.hpp
- vendor/libremidi/backends/coremidi.hpp
- vendor/libremidi/backends/coremidi/config.hpp
- vendor/libremidi/backends/coremidi/error_domain.hpp
- vendor/libremidi/backends/coremidi/helpers.hpp
- vendor/libremidi/backends/coremidi/midi_in.hpp
- vendor/libremidi/backends/coremidi/midi_out.hpp
- vendor/libremidi/backends/coremidi/observer.hpp
- vendor/libremidi/backends/coremidi_ump.hpp
- vendor/libremidi/backends/coremidi_ump/config.hpp
- vendor/libremidi/backends/coremidi_ump/helpers.hpp
- vendor/libremidi/backends/coremidi_ump/midi_in.hpp
- vendor/libremidi/backends/coremidi_ump/midi_out.hpp
- vendor/libremidi/backends/coremidi_ump/observer.hpp
- vendor/libremidi/backends/dummy.hpp
- vendor/libremidi/backends/emscripten.hpp
- vendor/libremidi/backends/emscripten/config.hpp
- vendor/libremidi/backends/emscripten/helpers.hpp
- vendor/libremidi/backends/emscripten/midi_access.hpp
- vendor/libremidi/backends/emscripten/midi_in.hpp
- vendor/libremidi/backends/emscripten/midi_out.hpp
- vendor/libremidi/backends/emscripten/observer.hpp
- vendor/libremidi/backends/jack.hpp
- vendor/libremidi/backends/jack/config.hpp
- vendor/libremidi/backends/jack/error_domain.hpp
- vendor/libremidi/backends/jack/helpers.hpp
- vendor/libremidi/backends/jack/midi_in.hpp
- vendor/libremidi/backends/jack/midi_out.hpp
- vendor/libremidi/backends/jack/observer.hpp
- vendor/libremidi/backends/jack/shared_handler.hpp
- vendor/libremidi/backends/keyboard.hpp
- vendor/libremidi/backends/keyboard/config.hpp
- vendor/libremidi/backends/keyboard/midi_in.hpp
- vendor/libremidi/backends/linux/alsa.hpp
- vendor/libremidi/backends/linux/dylib_loader.hpp
- vendor/libremidi/backends/linux/helpers.hpp
- vendor/libremidi/backends/linux/pipewire.hpp
- vendor/libremidi/backends/linux/udev.hpp
- vendor/libremidi/backends/net/config.hpp
- vendor/libremidi/backends/net/helpers.hpp
- vendor/libremidi/backends/net/midi_in.hpp
- vendor/libremidi/backends/net/midi_out.hpp
- vendor/libremidi/backends/net/observer.hpp
- vendor/libremidi/backends/network.hpp
- vendor/libremidi/backends/network_ump.hpp
- vendor/libremidi/backends/pipewire.hpp
- vendor/libremidi/backends/pipewire/config.hpp
- vendor/libremidi/backends/pipewire/context.hpp
- vendor/libremidi/backends/pipewire/helpers.hpp
- vendor/libremidi/backends/pipewire/midi_in.hpp
- vendor/libremidi/backends/pipewire/midi_out.hpp
- vendor/libremidi/backends/pipewire/observer.hpp
- vendor/libremidi/backends/pipewire/shared_handler.hpp
- vendor/libremidi/backends/winmidi.hpp
- vendor/libremidi/backends/winmidi/config.hpp
- vendor/libremidi/backends/winmidi/helpers.hpp
- vendor/libremidi/backends/winmidi/midi_in.hpp
- vendor/libremidi/backends/winmidi/midi_out.hpp
- vendor/libremidi/backends/winmidi/observer.hpp
- vendor/libremidi/backends/winmm.hpp
- vendor/libremidi/backends/winmm/config.hpp
- vendor/libremidi/backends/winmm/error_domain.hpp
- vendor/libremidi/backends/winmm/helpers.hpp
- vendor/libremidi/backends/winmm/midi_in.hpp
- vendor/libremidi/backends/winmm/midi_out.hpp
- vendor/libremidi/backends/winmm/observer.hpp
- vendor/libremidi/backends/winuwp.hpp
- vendor/libremidi/backends/winuwp/config.hpp
- vendor/libremidi/backends/winuwp/helpers.hpp
- vendor/libremidi/backends/winuwp/midi_in.hpp
- vendor/libremidi/backends/winuwp/midi_out.hpp
- vendor/libremidi/backends/winuwp/observer.hpp
- vendor/libremidi/client.hpp
- vendor/libremidi/cmidi2.hpp
- vendor/libremidi/config.hpp
- vendor/libremidi/configurations.hpp
- vendor/libremidi/defaults.hpp
- vendor/libremidi/detail/conversion.hpp
- vendor/libremidi/detail/memory.hpp
- vendor/libremidi/detail/midi_api.hpp
- vendor/libremidi/detail/midi_in.hpp
- vendor/libremidi/detail/midi_out.hpp
- vendor/libremidi/detail/midi_stream_decoder.hpp
- vendor/libremidi/detail/observer.hpp
- vendor/libremidi/detail/semaphore.hpp
- vendor/libremidi/detail/ump_stream.hpp
- vendor/libremidi/error.hpp
- vendor/libremidi/error_handler.hpp
- vendor/libremidi/input_configuration.hpp
- vendor/libremidi/libremidi.hpp
- vendor/libremidi/message.hpp
- vendor/libremidi/observer_configuration.hpp
- vendor/libremidi/output_configuration.hpp
- vendor/libremidi/reader.hpp
- vendor/libremidi/shared_context.hpp
- vendor/libremidi/system_error2.hpp
- vendor/libremidi/ump.hpp
- vendor/libremidi/writer.hpp

library:
  source-dirs: src
  extra-libraries:
  - stdc++
  include-dirs:
  - vendor
  cxx-sources:
  - vendor/libremidi/*.cpp
  when:
  - condition: os(darwin)
    cxx-options: -std=c++20 -DLIBREMIDI_COREMIDI=1
    frameworks: CoreMIDI CoreAudio CoreFoundation
  - condition: os(linux)
    cxx-options: -std=c++20 -DLIBREMIDI_PIPEWIRE=1 -DLIBREMIDI_HAS_UDEV=1
    pkgconfig-depends:
    - libpipewire-0.3
    - udev

executables:
  libremidi-exe:
    main: Main.hs
    source-dirs: exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - libremidi

tests:
  libremidi-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - libremidi
    - tasty
    - tasty-hunit
